### ISSUE TITLE
ViewActions still visible if 'View' tab is hidden

### ISSUE THREAD

**Issue by kixe** [adrianbj/RestrictTabView#1]
If the 'View' tab is set to hidden the ViewActions should be removed too.

```
$this->addHookBefore('ProcessPageEdit::getViewActions', function($e) {
	$e->replace = true;
	$e->return = array();
});
```
SCREENSHOT
![bildschirmfoto 2018-03-21 um 07 19 06](https://user-images.githubusercontent.com/4683120/37696651-8cce842c-2cd8-11e8-87b1-cb90a489f092.jpg)

**Comment by adrianbj** [comment]
Hey @kixe - I have mixed feelings about this. Firstly, just a heads up that the hook you mentioned doesn't affect the Save button, rather the dropdown from the View "tab".

I actually wonder if I should have ever included the options to hide the Content, View and Delete tabs at all. This module probably should just be able to hide the Settings tab - that was its real goal. Remember hiding the View tab and even the option from the Save button still doesn't prevent the using from viewing the page. There is also of course the View page list action button and of course go going directly to the URL. 

Can you give me a use case where it makes sense for a user to hide all these options? Maybe you have a template file but it's used as a partial but PW still sees it and adds the View links?

I am happy to implement if it makes sense!

**Comment by kixe** [comment]
I mean if you provide the option to hide the view tab in your module settings it should be really hidden instead of showing unexpected results.

My use case is a bit special. I am working on a convention planning app. The PW Backend will provide an Interface for speakers (authors) to apply for a contribution for this convention. Authors have very restricted access to the PW Backend (e.g. hidden pagetree). But they have page edit access for specified templates. During the call for contributions period, the frontend will be under development and will not be shown to anybody except developers. Therefore I would like to hide everything except content and delete tab.

I put the hook in ready and for me its fine now.

**Comment by adrianbj** [comment]
Sorry @kixe - I completely misunderstood the issue. I never use this module and I hadn't looked at it since the View tab dropdown of actions was added to the PW core.

I have implemented a fix, although I did it a little differently. It now removes the dropdown completely - with your hook I still had the border of the container showing. It also takes care of removing the "Save & View" option from the Save dropdown actions.

The one place where a "view" option remains is the Page Tree list actions, but I think that is beyond the scope of this module and sounds like it doesn't matter for you because you are hiding the page tree for these users anyway.

Please try the new version and let me know if you have any problems.
